credentials:
  api_key: Your_API_Key
  cse_id: Your_CSE_ID
detection_patterns:
  - SQL syntax.*error
  - Warning: .*MySQL
  - PostgreSQL.*ERROR
  - ORA-[0-9]{5}
  - Unclosed quotation mark
  - Syntax error in string literal
  - Microsoft OLE DB Provider
endpoints:
  google: https://www.googleapis.com/customsearch/v1
network:
  proxies: {}
  timeout: 10
payloads:
  mysql:
  - gAAAAABn6RJ6A-aBrJo_ZlI-SgAkEdQTmeYnN1BDZkvrUZEos6NY1te6TqSGGiwGkPYxfoXoH8J6Ye7WyIMhe9hKiD-NtvgwDA==
  - gAAAAABn6RJ6H9y33m87wEJAfHNdjncAptI1CGw5xjrKVfET4uWni9XMItY1FoukhXaRX96-kafe8s-vthEg-QLYatnuxvCF6qNJ1glJVUsPriy4k1ZDXUU=
  - gAAAAABn6RJ63bnNcISQ7uCpeg5IIXMI3oHkOwab-b1iDnuFSNCu868B2fUmyGpjFHrmY6sNjhuQ1QkMyOlnbvycTsridfe02a_O5phu7dc35JzG1U4KMYA=
  postgresql:
  - gAAAAABn6RJ6j6X3Je_WLAH264_34tFW7ksLYjAjcU4JZLb4agqRgAIDM7XqOCsmpdS9rsASDR8zIGvTekuRNYTBOh7M4lIiMQ==
  - gAAAAABn6RJ6kfSDnTHI4bAwoMvTpwNKiIXhSgjtP_Joqkq6ony3xHLwqV3ZQ-UepmdKJ1yFzrnjdG05vuu7t7rTLFL2Y1iHeypAlONJVSG2h5Isa283fFvA_YeJJ9xl6hWXP_shacDu
  - gAAAAABn6RJ6K2UVHUeBg19TAhy_QWUPHFxlSFva0OuFghfciBqf8j1_pW76gGpX_n1HoeOT4jnrcWz8pTZ9tvLkkCA00_H8NfgqAGK17TnhrL9vBFvIsHCj7XJMbx97nLbHI-pOHTsdErsOEkntkXoAg075Ydy-IQ==
performance:
  threads: 10
security:
  encryption_key: PSq4P3X261FcFtZjesEGchzDNv3T2SUtYH0eCZuTtrE=
stealth:
  referers:
  - https://google.com
  time_based_threshold: 3.5
